# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  # branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: Watashinokage/git-repository-test
          fetch-tags: true

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a single command using the runners shell
      - name: Run pwd
        run: pwd

      # Runs a single command using the runners shell
      - name: Run ls
        run: ls -a

      # Runs a single command using the runners shell
      - name: Run git tag
        run: |
          readarray -t my_tags < <(git tag)
          declare -p my_tags
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "multiline"
          tagname=v1.2
          echo $tag_name
          readarray -t my_array < <(git diff-tree --no-commit-id --name-only -t $tagname)
          echo ${my_array[@]}
          for i in "${my_array[@]}"
          do
           echo "$i $tagname"
           mv "$i" "$tagname"__"$i"
          done
          mv scripA.sql scriptAAA.sql
        env:
          tagname: v1.2

      # Runs a single command using the runners shell
      - name: Run ls finale
        run: ls -a
